### ISSUE TITLE
Organize project documentation into sections

### ISSUE THREAD

**Issue by DigitalArcPlatform** [DigitalArcPlatform/documentation#2]
Create new documentation sections that reflect chronology of holding and launching a community archive: pre-event, during-event, post-event and platform-installation

**Comment by DigitalArcPlatform** [comment]
Alec completed most of this work during summer 2024 and can be found on the project's Google Drive (login through project email): https://drive.google.com/drive/folders/1gYudoS6hiHPNt8NwlZ2NH804yb2l5DrC?usp=share_link

**Comment by FredFuchs387** [comment]
The documentation has been organized into sections.
